### ISSUE TITLE
Migrer begrepsdata Brreg

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/concept-etl#4]
- Extract begrep fra fil
- Transformasjon til begrep som JSON
- Lagre til Mongo i Concept catalog

**Comment by valosnah** [comment]
Migreringsdato satt: tirsdag 6. februar

**Comment by valosnah** [comment]
Begrep migrert til concept-catalog
Kommentarer migrert til catalog-comments-service
Historikk migrert til catalog-history-service
Brukere migrert til hhv catalog-admin-service og catalog-comments-service (Kun som placeholders, all fremtidig bruk i vår løsning blir via brukere opprette ifm Brreg Azure AD)
