### ISSUE TITLE
Dokumentere mapping fra brreg og skatt til begrepskatalogen

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/concept-etl#6]
TODO: 
- [x] Dokumentere mapping fra skatt sin katalog til begrepskatalogen
- [x] Dokumentere mapping fra Brreg sin katalog til begrepskatalogen

**Comment by valosnah** [comment]
Laget to dokumenter i teams
Tar en gjennomgang med @NilsOveTen
